descriptor_extension: yml
version: "0.5"
files:
  - path: comm-pilot-nsd.yml
    type: application/vnd.5gtango.nsd
    tags:
      - eu.5gtango
  - path: wac-vnf_01.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_02.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_03.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_04.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_05.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_06.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_07.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_08.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
  - path: wac-vnf_09.yml
    type: application/vnd.5gtango.vnfd
    tags:
      - eu.5gtango
package:
  description: Communication Pilot
  maintainer: Ana Pol, Quobis, ana.pol@quobis.com
  name: "communication-pilot"
  vendor: "quobis"
  version: "0.5"
